---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    fish_setup_mcfly: false
    fish_configure_users:
      - ubuntu

  tasks:
    - name: Include fish role
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
